-- MySQL Script generated by MySQL Workbench
-- 05/13/15 12:36:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema autocapital
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `autocapital` ;

-- -----------------------------------------------------
-- Schema autocapital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autocapital` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `autocapital` ;

-- -----------------------------------------------------
-- Table `autocapital`.`activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`activities` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`activities` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `parent` INT(11) NULL DEFAULT NULL COMMENT 'Parent activity id',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_parent`
    FOREIGN KEY (`parent`)
    REFERENCES `autocapital`.`activities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8
COMMENT = 'Направления деятельности';

CREATE INDEX `fk_parent_idx` ON `autocapital`.`activities` (`parent` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`users` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `salt` VARCHAR(10) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `second_name` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `is_male` TINYINT(1) NULL DEFAULT '1' COMMENT 'муж�',
  `date_registration` TIMESTAMP NULL DEFAULT NULL COMMENT 'дата регистрации в системе',
  `birthday` DATE NULL DEFAULT NULL COMMENT 'день ро',
  `phome` VARCHAR(45) NULL DEFAULT NULL COMMENT 'домашний ',
  `pmobile` VARCHAR(45) NULL DEFAULT NULL COMMENT 'мобильный',
  `address_home` VARCHAR(255) NULL DEFAULT NULL COMMENT 'домашни�',
  `photo_src` VARCHAR(255) NULL DEFAULT NULL COMMENT 'персональ',
  `old_id` INT(11) NULL DEFAULT NULL,
  `is_active` TINYINT(4) NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COMMENT = 'Пользователи системы';


-- -----------------------------------------------------
-- Table `autocapital`.`activities_methodists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`activities_methodists` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`activities_methodists` (
  `activity_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`activity_id`, `user_id`),
  CONSTRAINT `activities_methodists_ibfk_1`
    FOREIGN KEY (`activity_id`)
    REFERENCES `autocapital`.`activities` (`id`),
  CONSTRAINT `activities_methodists_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `autocapital`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Связь доступных методистам напр. деятельности';

CREATE INDEX `am_activity_id_idx` ON `autocapital`.`activities_methodists` (`activity_id` ASC);

CREATE INDEX `am_user_id_idx` ON `autocapital`.`activities_methodists` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`brands` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`brands` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `old_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8
COMMENT = 'Все возможные бренды';


-- -----------------------------------------------------
-- Table `autocapital`.`brands_methodists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`brands_methodists` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`brands_methodists` (
  `brand_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`brand_id`, `user_id`),
  CONSTRAINT `brands_methodists_ibfk_1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `autocapital`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `brands_methodists_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `autocapital`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Связь бренды пользователей-методистов';

CREATE INDEX `dm_brand_id_idx` ON `autocapital`.`brands_methodists` (`brand_id` ASC);

CREATE INDEX `dm_user_id_idx` ON `autocapital`.`brands_methodists` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`region` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`region` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `old_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8
COMMENT = 'Области Украины';


-- -----------------------------------------------------
-- Table `autocapital`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`city` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`city` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `region_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `phone_code` VARCHAR(7) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `city_ibfk_1`
    FOREIGN KEY (`region_id`)
    REFERENCES `autocapital`.`region` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 636
DEFAULT CHARACTER SET = utf8
COMMENT = 'Города, с привязкой к областям';

CREATE INDEX `index2` ON `autocapital`.`city` (`region_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`company` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`company` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COMMENT = 'Дилерские компании';


-- -----------------------------------------------------
-- Table `autocapital`.`company_activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`company_activities` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`company_activities` (
  `company_id` INT(11) NOT NULL,
  `activity_id` INT(11) NOT NULL,
  PRIMARY KEY (`company_id`, `activity_id`),
  CONSTRAINT `fk_company_activities_1`
    FOREIGN KEY (`company_id`)
    REFERENCES `autocapital`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_activities_2`
    FOREIGN KEY (`activity_id`)
    REFERENCES `autocapital`.`activities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Связь напр. деятельности ДК';

CREATE INDEX `fk_company_activities_1_idx` ON `autocapital`.`company_activities` (`company_id` ASC);

CREATE INDEX `fk_company_activities_2_idx` ON `autocapital`.`company_activities` (`activity_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`company_brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`company_brands` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`company_brands` (
  `company_id` INT(11) NOT NULL,
  `brand_id` INT(11) NOT NULL,
  PRIMARY KEY (`company_id`, `brand_id`),
  CONSTRAINT `fk_company_brands_1`
    FOREIGN KEY (`company_id`)
    REFERENCES `autocapital`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_brands_2`
    FOREIGN KEY (`brand_id`)
    REFERENCES `autocapital`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Связь бренды ДК';

CREATE INDEX `fk_company_brands_1_idx` ON `autocapital`.`company_brands` (`company_id` ASC);

CREATE INDEX `fk_company_brands_2_idx` ON `autocapital`.`company_brands` (`brand_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`company_methodists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`company_methodists` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`company_methodists` (
  `company_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`company_id`, `user_id`),
  CONSTRAINT `fk_company_id`
    FOREIGN KEY (`company_id`)
    REFERENCES `autocapital`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `autocapital`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Связь пользователи-методисты ДК';

CREATE INDEX `company_id` ON `autocapital`.`company_methodists` (`company_id` ASC);

CREATE INDEX `user_id` ON `autocapital`.`company_methodists` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`courses_sections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`courses_sections` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`courses_sections` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created` DATETIME NULL DEFAULT NULL,
  `is_active` INT(1) NULL DEFAULT NULL,
  `sort` INT(11) NULL DEFAULT NULL,
  `title` TEXT NULL DEFAULT NULL,
  `old_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Разделы курсов';


-- -----------------------------------------------------
-- Table `autocapital`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`courses` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`courses` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created` DATETIME NULL DEFAULT NULL,
  `is_active` TINYINT(1) NULL DEFAULT '0',
  `section` INT(11) NULL DEFAULT NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `preview_picture` INT(11) NULL DEFAULT NULL,
  `preview_text` LONGTEXT NULL DEFAULT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `active_from` DATETIME NULL DEFAULT NULL,
  `active_to` DATETIME NULL DEFAULT NULL,
  `old_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `c_section`
    FOREIGN KEY (`section`)
    REFERENCES `autocapital`.`courses_sections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Курсы';

CREATE INDEX `c_section_idx` ON `autocapital`.`courses` (`section` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`courses_activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`courses_activities` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`courses_activities` (
  `activity_id` INT(11) NOT NULL,
  `course_id` INT(11) NOT NULL,
  PRIMARY KEY (`activity_id`, `course_id`),
  CONSTRAINT `ca_activitiy_id`
    FOREIGN KEY (`activity_id`)
    REFERENCES `autocapital`.`activities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ca_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `autocapital`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Связь напр. деятельности курсов';

CREATE INDEX `ind_ca_activitiy_id` ON `autocapital`.`courses_activities` (`activity_id` ASC);

CREATE INDEX `ind_ca_course_id` ON `autocapital`.`courses_activities` (`course_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`courses_brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`courses_brands` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`courses_brands` (
  `brand_id` INT(11) NOT NULL,
  `course_id` INT(11) NOT NULL,
  PRIMARY KEY (`brand_id`, `course_id`),
  CONSTRAINT `cb_brand_id`
    FOREIGN KEY (`brand_id`)
    REFERENCES `autocapital`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cb_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `autocapital`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Связь бренды курсов';

CREATE INDEX `brand_id_idx` ON `autocapital`.`courses_brands` (`brand_id` ASC);

CREATE INDEX `cb_course_id_idx` ON `autocapital`.`courses_brands` (`course_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`courses_chapters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`courses_chapters` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`courses_chapters` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created` DATETIME NULL DEFAULT NULL,
  `is_active` TINYINT(1) NULL DEFAULT NULL,
  `course_id` INT(11) NULL DEFAULT NULL,
  `chapter_id` INT(11) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `preview` LONGTEXT NULL DEFAULT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `old_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `cch_chapter_id`
    FOREIGN KEY (`chapter_id`)
    REFERENCES `autocapital`.`courses_chapters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cch_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `autocapital`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Главы курсов';

CREATE INDEX `ch_chapter_id_idx` ON `autocapital`.`courses_chapters` (`chapter_id` ASC);

CREATE INDEX `cch_course_id_idx` ON `autocapital`.`courses_chapters` (`course_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`direction_study_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`direction_study_groups` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`direction_study_groups` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COMMENT = 'Группы направления обучения. Создана для отделения основный  /* comment truncated */ /* /* comment truncated */ /*7 должностей от других должностей.*/*/';


-- -----------------------------------------------------
-- Table `autocapital`.`direction_study`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`direction_study` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`direction_study` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `direction_study_group_id` INT(11) NULL DEFAULT NULL COMMENT 'Группа направл',
  `is_managerial_position` TINYINT(1) NULL DEFAULT '0' COMMENT 'Руководяща�',
  `old_position_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_direction_study_1`
    FOREIGN KEY (`direction_study_group_id`)
    REFERENCES `autocapital`.`direction_study_groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = 'Направления обучения';

CREATE INDEX `index2` ON `autocapital`.`direction_study` (`direction_study_group_id` ASC);

CREATE INDEX `index3` ON `autocapital`.`direction_study` (`is_managerial_position` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`courses_direction_study`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`courses_direction_study` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`courses_direction_study` (
  `direction_study_id` INT(11) NOT NULL,
  `course_id` INT(11) NOT NULL,
  PRIMARY KEY (`direction_study_id`, `course_id`),
  CONSTRAINT `cds_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `autocapital`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cds_direction_study_id`
    FOREIGN KEY (`direction_study_id`)
    REFERENCES `autocapital`.`direction_study` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Связь напрв. обучения курсов';

CREATE INDEX `direction_study_id_idx` ON `autocapital`.`courses_direction_study` (`direction_study_id` ASC);

CREATE INDEX `course_id_idx` ON `autocapital`.`courses_direction_study` (`course_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`courses_lessons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`courses_lessons` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`courses_lessons` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created` DATETIME NULL DEFAULT NULL,
  `is_active` INT(1) NULL DEFAULT NULL,
  `course_id` INT(11) NULL DEFAULT NULL,
  `chapter_id` INT(11) NULL DEFAULT NULL,
  `title` TEXT NULL DEFAULT NULL,
  `preview` TEXT NULL DEFAULT NULL,
  `detail` LONGTEXT NULL DEFAULT NULL,
  `old_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `cl_chapter_id`
    FOREIGN KEY (`chapter_id`)
    REFERENCES `autocapital`.`courses_chapters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cl_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `autocapital`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Связь уроки курсов';

CREATE INDEX `cl_chapter_id_idx` ON `autocapital`.`courses_lessons` (`chapter_id` ASC);

CREATE INDEX `cl_course_id_idx` ON `autocapital`.`courses_lessons` (`course_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`dealer_statuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`dealer_statuses` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`dealer_statuses` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COMMENT = 'Статусы предприятий';


-- -----------------------------------------------------
-- Table `autocapital`.`stafflist_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`stafflist_group` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`stafflist_group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `old_id` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COMMENT = 'Шаблоны штатного рассписания ';


-- -----------------------------------------------------
-- Table `autocapital`.`dealers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`dealers` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`dealers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Название п�',
  `city_id` INT(11) NULL DEFAULT NULL COMMENT 'Город',
  `address` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Адрес предприятия',
  `parent_id` INT(11) NULL DEFAULT NULL COMMENT 'Главное предприятие',
  `stafflist_group_id` INT(11) NULL DEFAULT NULL COMMENT 'Штатное ра',
  `status` INT(11) NULL DEFAULT NULL,
  `old_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `dealers_ibfk_1`
    FOREIGN KEY (`city_id`)
    REFERENCES `autocapital`.`city` (`id`),
  CONSTRAINT `fk_dealer_status`
    FOREIGN KEY (`status`)
    REFERENCES `autocapital`.`dealer_statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dealers_1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `autocapital`.`dealers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dealers_2`
    FOREIGN KEY (`stafflist_group_id`)
    REFERENCES `autocapital`.`stafflist_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 200
DEFAULT CHARACTER SET = utf8
COMMENT = 'Предприятия';

CREATE INDEX `index2` ON `autocapital`.`dealers` (`stafflist_group_id` ASC);

CREATE INDEX `index3` ON `autocapital`.`dealers` (`parent_id` ASC);

CREATE INDEX `index4` ON `autocapital`.`dealers` (`city_id` ASC);

CREATE INDEX `status_ind` ON `autocapital`.`dealers` (`status` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`dealers_activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`dealers_activities` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`dealers_activities` (
  `activity_id` INT(11) NOT NULL,
  `dealer_id` INT(11) NOT NULL,
  PRIMARY KEY (`activity_id`, `dealer_id`),
  CONSTRAINT `fk_dealers_activities_1`
    FOREIGN KEY (`activity_id`)
    REFERENCES `autocapital`.`activities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dealers_activities_2`
    FOREIGN KEY (`dealer_id`)
    REFERENCES `autocapital`.`dealers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Связь напр. деятельности предприятий';

CREATE INDEX `fk_dealers_brands_1_idx` ON `autocapital`.`dealers_activities` (`activity_id` ASC);

CREATE INDEX `fk_dealers_brands_2_idx` ON `autocapital`.`dealers_activities` (`dealer_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`dealers_brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`dealers_brands` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`dealers_brands` (
  `brand_id` INT(11) NOT NULL,
  `dealer_id` INT(11) NOT NULL,
  PRIMARY KEY (`brand_id`, `dealer_id`),
  CONSTRAINT `fk_dealers_brands_1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `autocapital`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dealers_brands_2`
    FOREIGN KEY (`dealer_id`)
    REFERENCES `autocapital`.`dealers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Связь бренды предприятий';

CREATE INDEX `fk_dealers_brands_1_idx` ON `autocapital`.`dealers_brands` (`brand_id` ASC);

CREATE INDEX `fk_dealers_brands_2_idx` ON `autocapital`.`dealers_brands` (`dealer_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`educations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`educations` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`educations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `parent_id` INT(11) NULL DEFAULT NULL,
  `old_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `parent_id`
    FOREIGN KEY (`parent_id`)
    REFERENCES `autocapital`.`educations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Типы образований с родителями (напр. Высшее, Специалист)';

CREATE INDEX `parent_id_idx` ON `autocapital`.`educations` (`parent_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`groups` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`groups` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Название',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COMMENT = 'Группы пользователей ';


-- -----------------------------------------------------
-- Table `autocapital`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`posts` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `alias` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Список всех доложностей (например из Кадастра Должностей), привязанные к направлениям обучения';


-- -----------------------------------------------------
-- Table `autocapital`.`stafflist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`stafflist` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`stafflist` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `post` INT(11) NULL,
  `direction_study` INT(11) NULL DEFAULT NULL,
  `stafflist_group` INT(11) NULL DEFAULT NULL,
  `parent` VARCHAR(255) NULL DEFAULT NULL COMMENT 'вида 1.3.12 ',
  `department_title` VARCHAR(255) NULL,
  `staff_old_id` INT(11) NOT NULL,
  `parent_old_id` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  CONSTRAINT `s_stafflist_group_fk`
    FOREIGN KEY (`stafflist_group`)
    REFERENCES `autocapital`.`stafflist_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `s_post_fk`
    FOREIGN KEY (`post`)
    REFERENCES `autocapital`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `s_direction_study`
    FOREIGN KEY (`direction_study`)
    REFERENCES `autocapital`.`direction_study` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Штатное расписание';

CREATE INDEX `s_parent_idx` ON `autocapital`.`stafflist` (`parent` ASC);

CREATE INDEX `s_stafflist_group_idx` ON `autocapital`.`stafflist` (`stafflist_group` ASC);

CREATE INDEX `s_post_idx` ON `autocapital`.`stafflist` (`post` ASC);

CREATE INDEX `s_direction_study_idx` ON `autocapital`.`stafflist` (`direction_study` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`stafflist_post_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`stafflist_post_plan` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`stafflist_post_plan` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `stafflist` INT(11) NULL DEFAULT NULL,
  `dealer` INT(11) NULL DEFAULT NULL,
  `activity` INT(11) NULL DEFAULT NULL,
  `brand` INT(11) NULL DEFAULT NULL,
  `post_plan_count` INT(11) NULL DEFAULT NULL COMMENT 'Плановое количество по должности',
  `post_plan_total_count` INT(11) NULL DEFAULT NULL COMMENT 'Плановое количество всего ',
  PRIMARY KEY (`id`),
  CONSTRAINT `spp_stafflist_fk`
    FOREIGN KEY (`stafflist`)
    REFERENCES `autocapital`.`stafflist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `spp_brands_fk`
    FOREIGN KEY (`brand`)
    REFERENCES `autocapital`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `spp_dealers_fk`
    FOREIGN KEY (`dealer`)
    REFERENCES `autocapital`.`dealers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `spp_activity_fk`
    FOREIGN KEY (`activity`)
    REFERENCES `autocapital`.`activities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Плановое количество  должностей ';

CREATE INDEX `spp_stafflist_idx` ON `autocapital`.`stafflist_post_plan` (`stafflist` ASC);

CREATE INDEX `spp_brand_idx` ON `autocapital`.`stafflist_post_plan` (`brand` ASC);

CREATE INDEX `spp_dealer_idx` ON `autocapital`.`stafflist_post_plan` (`dealer` ASC);

CREATE INDEX `spp_activity_idx` ON `autocapital`.`stafflist_post_plan` (`activity` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`qualification_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`qualification_group` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`qualification_group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL COMMENT 'название для групп квалификаций',
  `parent_id` INT(11) NULL DEFAULT NULL COMMENT 'Нужно для иерархии квалификаций',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_qualification_group_1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `autocapital`.`qualification_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Группы квалификаций (напр. Базовая, Средняя)';

CREATE INDEX `index2` ON `autocapital`.`qualification_group` (`parent_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`qualification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`qualification` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`qualification` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `qualification_group_id` INT(11) NOT NULL COMMENT 'Группа квалификации',
  `direction_study_id` INT(11) NOT NULL COMMENT 'Для направления обучения',
  `date_start` DATE NOT NULL COMMENT 'Начало старта',
  `date_end` DATE NOT NULL COMMENT 'Дата окончания автивности квалификации',
  `test_id` INT(11) NULL DEFAULT NULL COMMENT 'Квалификационный тест, доступный при прох. всех дист. и стац. курсов',
  `seminar_id` INT(11) NULL DEFAULT NULL COMMENT 'Квалификационный тест (стационарный - оценка за семинар), доступный при прох. всех дист. и стац. курсов',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_qualification_1`
    FOREIGN KEY (`direction_study_id`)
    REFERENCES `autocapital`.`direction_study` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_qualification_2`
    FOREIGN KEY (`qualification_group_id`)
    REFERENCES `autocapital`.`qualification_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Квалификации (с призязкой к периодам и т.д.)';

CREATE INDEX `index2` ON `autocapital`.`qualification` (`direction_study_id` ASC);

CREATE INDEX `index3` ON `autocapital`.`qualification` (`qualification_group_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`qualification_activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`qualification_activities` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`qualification_activities` (
  `qualification_id` INT(11) NOT NULL,
  `activity_id` INT(11) NOT NULL,
  PRIMARY KEY (`qualification_id`, `activity_id`),
  CONSTRAINT `fk_qualification_activities_1`
    FOREIGN KEY (`qualification_id`)
    REFERENCES `autocapital`.`qualification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_qualification_activities_2`
    FOREIGN KEY (`activity_id`)
    REFERENCES `autocapital`.`activities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Связь напр. деятельности квалификаций';

CREATE INDEX `index1` ON `autocapital`.`qualification_activities` (`qualification_id` ASC);

CREATE INDEX `fk_qualification_activities_2_idx` ON `autocapital`.`qualification_activities` (`activity_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`qualification_brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`qualification_brands` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`qualification_brands` (
  `qualification_id` INT(11) NOT NULL,
  `brand_id` INT(11) NOT NULL,
  PRIMARY KEY (`qualification_id`, `brand_id`),
  CONSTRAINT `fk_qualification_brands_1`
    FOREIGN KEY (`qualification_id`)
    REFERENCES `autocapital`.`qualification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_qualification_brands_2`
    FOREIGN KEY (`brand_id`)
    REFERENCES `autocapital`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Связь брендов квалификаций';

CREATE INDEX `index1` ON `autocapital`.`qualification_brands` (`qualification_id` ASC);

CREATE INDEX `index2` ON `autocapital`.`qualification_brands` (`brand_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`qualification_courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`qualification_courses` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`qualification_courses` (
  `course_id` INT(11) NOT NULL,
  `qualification_id` INT(11) NOT NULL,
  PRIMARY KEY (`course_id`, `qualification_id`),
  CONSTRAINT `fk_qualification_courses_1`
    FOREIGN KEY (`qualification_id`)
    REFERENCES `autocapital`.`qualification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_qualification_courses_2`
    FOREIGN KEY (`course_id`)
    REFERENCES `autocapital`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Связь курсы(дистанц.) квалификаций';

CREATE INDEX `index1` ON `autocapital`.`qualification_courses` (`course_id` ASC);

CREATE INDEX `index2` ON `autocapital`.`qualification_courses` (`qualification_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`stat_courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`stat_courses` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`stat_courses` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created` DATETIME NULL DEFAULT NULL,
  `is_active` TINYINT(1) NULL DEFAULT '0',
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `preview_picture` INT(11) NULL DEFAULT NULL,
  `preview_text` LONGTEXT NULL DEFAULT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `active_from` DATETIME NULL DEFAULT NULL,
  `active_to` DATETIME NULL DEFAULT NULL,
  `old_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Стационарные курсы';


-- -----------------------------------------------------
-- Table `autocapital`.`qualification_courses_stat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`qualification_courses_stat` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`qualification_courses_stat` (
  `qualification_id` INT(11) NOT NULL,
  `stat_course_id` INT(11) NOT NULL,
  PRIMARY KEY (`qualification_id`, `stat_course_id`),
  CONSTRAINT `fk_qualification_courses_stat_1`
    FOREIGN KEY (`stat_course_id`)
    REFERENCES `autocapital`.`stat_courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_qualification_courses_stat_2`
    FOREIGN KEY (`qualification_id`)
    REFERENCES `autocapital`.`qualification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Связь курсы(стац.) квалификаций';

CREATE INDEX `index1` ON `autocapital`.`qualification_courses_stat` (`qualification_id` ASC);

CREATE INDEX `index2` ON `autocapital`.`qualification_courses_stat` (`stat_course_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`students` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`students` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `ind_code` VARCHAR(11) NULL DEFAULT NULL COMMENT 'идентификационный код',
  `sheet_staff` VARCHAR(255) NULL DEFAULT NULL COMMENT 'лист з обліку кадрів',
  `order_accept` VARCHAR(255) NULL DEFAULT NULL COMMENT 'наказ про прийняття на роботу',
  `post_for_display` VARCHAR(255) NULL DEFAULT NULL COMMENT 'должность для отображения',
  `old_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_students_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `autocapital`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = 'Студенты';

CREATE INDEX `fk_students_1_idx` ON `autocapital`.`students` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`qualification_students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`qualification_students` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`qualification_students` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL COMMENT 'Дата получения квалификации',
  `student_id` INT(11) NOT NULL,
  `qualification_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_qualification_students_1`
    FOREIGN KEY (`student_id`)
    REFERENCES `autocapital`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_qualification_students_2`
    FOREIGN KEY (`qualification_id`)
    REFERENCES `autocapital`.`qualification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Наличие квалификации у студентов';

CREATE INDEX `index2` ON `autocapital`.`qualification_students` (`student_id` ASC);

CREATE INDEX `index3` ON `autocapital`.`qualification_students` (`qualification_id` ASC);

CREATE INDEX `index4` ON `autocapital`.`qualification_students` (`date` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`seminars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`seminars` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`seminars` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created` DATETIME NULL DEFAULT NULL,
  `is_active` TINYINT(1) NULL DEFAULT '0',
  `stat_course` INT(11) NULL DEFAULT NULL,
  `capacity` INT(11) NULL DEFAULT '0',
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `preview_picture` INT(11) NULL DEFAULT NULL,
  `preview_text` LONGTEXT NULL DEFAULT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `date_start` DATETIME NULL DEFAULT NULL,
  `date_end` DATETIME NULL DEFAULT NULL,
  `old_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `s_stat_course`
    FOREIGN KEY (`stat_course`)
    REFERENCES `autocapital`.`stat_courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Семинары';

CREATE INDEX `s_course` ON `autocapital`.`seminars` (`stat_course` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`seminars_marks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`seminars_marks` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`seminars_marks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `seminar_id` INT(11) NULL DEFAULT NULL,
  `student_id` INT(11) NULL DEFAULT NULL,
  `mark` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `sm_seminar`
    FOREIGN KEY (`seminar_id`)
    REFERENCES `autocapital`.`seminars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sm_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `autocapital`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Оценки за семинары';

CREATE INDEX `seminar_idx` ON `autocapital`.`seminars_marks` (`seminar_id` ASC);

CREATE INDEX `student_idx` ON `autocapital`.`seminars_marks` (`student_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`seminars_students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`seminars_students` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`seminars_students` (
  `seminar_id` INT(11) NOT NULL,
  `student_id` INT(11) NOT NULL,
  PRIMARY KEY (`seminar_id`, `student_id`),
  CONSTRAINT `ss_seminar`
    FOREIGN KEY (`seminar_id`)
    REFERENCES `autocapital`.`seminars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ss_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `autocapital`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Связь студенты семинаров';

CREATE INDEX `seminar_idx` ON `autocapital`.`seminars_students` (`seminar_id` ASC);

CREATE INDEX `student_idx` ON `autocapital`.`seminars_students` (`student_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`stat_courses_activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`stat_courses_activities` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`stat_courses_activities` (
  `activity_id` INT(11) NOT NULL,
  `stat_course_id` INT(11) NOT NULL,
  PRIMARY KEY (`activity_id`, `stat_course_id`),
  CONSTRAINT `sca_activity_id`
    FOREIGN KEY (`activity_id`)
    REFERENCES `autocapital`.`activities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sca_stat_course_id`
    FOREIGN KEY (`stat_course_id`)
    REFERENCES `autocapital`.`stat_courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Связь напр. деят. стац. курсов';

CREATE INDEX `sca_course_id_idx` ON `autocapital`.`stat_courses_activities` (`stat_course_id` ASC);

CREATE INDEX `sca_activity_id_idx` ON `autocapital`.`stat_courses_activities` (`activity_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`stat_courses_brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`stat_courses_brands` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`stat_courses_brands` (
  `brand_id` INT(11) NOT NULL,
  `stat_course_id` INT(11) NOT NULL,
  PRIMARY KEY (`brand_id`, `stat_course_id`),
  CONSTRAINT `scb_brand_id`
    FOREIGN KEY (`brand_id`)
    REFERENCES `autocapital`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `scb_stat_course_id`
    FOREIGN KEY (`stat_course_id`)
    REFERENCES `autocapital`.`stat_courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Связь бренды стац. курсов';

CREATE INDEX `brand_id_idx` ON `autocapital`.`stat_courses_brands` (`brand_id` ASC);

CREATE INDEX `course_id_idx` ON `autocapital`.`stat_courses_brands` (`stat_course_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`stat_courses_direction_study`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`stat_courses_direction_study` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`stat_courses_direction_study` (
  `direction_study_id` INT(11) NOT NULL,
  `stat_course_id` INT(11) NOT NULL,
  PRIMARY KEY (`direction_study_id`, `stat_course_id`),
  CONSTRAINT `scds_direction_study_id`
    FOREIGN KEY (`direction_study_id`)
    REFERENCES `autocapital`.`direction_study` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `scds_stat_course_id`
    FOREIGN KEY (`stat_course_id`)
    REFERENCES `autocapital`.`stat_courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Связь напр. обучения стац. курсов';

CREATE INDEX `direction_study_id_idx` ON `autocapital`.`stat_courses_direction_study` (`direction_study_id` ASC);

CREATE INDEX `course_id_idx` ON `autocapital`.`stat_courses_direction_study` (`stat_course_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`students_posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`students_posts` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`students_posts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `student` INT(11) NOT NULL,
  `rate` DOUBLE NULL COMMENT 'Ставка на должность ',
  `post` INT(11) NULL COMMENT 'Должность',
  `dealer` INT(11) NULL COMMENT 'На каком предприятии зарегистрирован пользователь',
  `activity` INT(11) NULL DEFAULT '1' COMMENT 'Напр. деятельности',
  `appoint_date` DATE NULL COMMENT 'Дата назначения на должность',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_students_abilities_ds`
    FOREIGN KEY (`post`)
    REFERENCES `autocapital`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_abilities_dealer`
    FOREIGN KEY (`dealer`)
    REFERENCES `autocapital`.`dealers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_abilities_student`
    FOREIGN KEY (`student`)
    REFERENCES `autocapital`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_abilities_activity`
    FOREIGN KEY (`activity`)
    REFERENCES `autocapital`.`activities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COMMENT = 'Должностные данные о студентах';

CREATE INDEX `fk_students_abilities_2_idx` ON `autocapital`.`students_posts` (`dealer` ASC);

CREATE INDEX `fk_students_abilities_3_idx` ON `autocapital`.`students_posts` (`student` ASC);

CREATE INDEX `fk_students_abilities_4_idx` ON `autocapital`.`students_posts` (`activity` ASC);

CREATE INDEX `fk_students_abilities_ds_idx` ON `autocapital`.`students_posts` (`post` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`students_posts_brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`students_posts_brands` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`students_posts_brands` (
  `student_post_id` INT(11) NOT NULL,
  `brand_id` INT(11) NOT NULL,
  CONSTRAINT `fk_students_brands_1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `autocapital`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_brands_2`
    FOREIGN KEY (`student_post_id`)
    REFERENCES `autocapital`.`students_posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Связь бренды студентов';

CREATE INDEX `fk_students_brands_1_idx` ON `autocapital`.`students_posts_brands` (`brand_id` ASC);

CREATE INDEX `fk_students_brands_2_idx` ON `autocapital`.`students_posts_brands` (`student_post_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`students_certifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`students_certifications` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`students_certifications` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_id` INT(11) NOT NULL,
  `course_id` INT(11) NOT NULL,
  `date` DATETIME NOT NULL COMMENT 'Дата сдачи',
  `mark` TINYINT(4) NOT NULL COMMENT 'оценка за курс',
  `mark_max` TINYINT(4) NOT NULL COMMENT 'максимально возможная оценка ',
  `mark_percent` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_students_certifications_1`
    FOREIGN KEY (`student_id`)
    REFERENCES `autocapital`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_certifications_2`
    FOREIGN KEY (`course_id`)
    REFERENCES `autocapital`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Сертификация студентов (рудимент со старой системы)';

CREATE INDEX `index2` ON `autocapital`.`students_certifications` (`student_id` ASC);

CREATE INDEX `index3` ON `autocapital`.`students_certifications` (`course_id` ASC);

CREATE INDEX `index4` ON `autocapital`.`students_certifications` (`date` ASC);

CREATE INDEX `index5` ON `autocapital`.`students_certifications` (`mark` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`students_education`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`students_education` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`students_education` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_id` INT(11) NULL DEFAULT NULL,
  `education_id` INT(11) NULL DEFAULT NULL,
  `institution` VARCHAR(255) NULL DEFAULT NULL,
  `diploma_number` VARCHAR(45) NULL DEFAULT NULL,
  `diploma_date` DATE NULL DEFAULT NULL,
  `speciality` VARCHAR(255) NULL DEFAULT NULL,
  `qualify` VARCHAR(255) NULL DEFAULT NULL,
  `old_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `education_id`
    FOREIGN KEY (`education_id`)
    REFERENCES `autocapital`.`educations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `autocapital`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Образования студентов';

CREATE INDEX `student_id_idx` ON `autocapital`.`students_education` (`student_id` ASC);

CREATE INDEX `education_id_idx` ON `autocapital`.`students_education` (`education_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`students_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`students_status` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`students_status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_id` INT(11) NOT NULL,
  `brand_id` INT(11) NOT NULL,
  `is_main` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_students_status_1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `autocapital`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_status_2`
    FOREIGN KEY (`student_id`)
    REFERENCES `autocapital`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Статусы студентов (привязка к бренду)';

CREATE INDEX `index2` ON `autocapital`.`students_status` (`student_id` ASC);

CREATE INDEX `index3` ON `autocapital`.`students_status` (`brand_id` ASC);

CREATE INDEX `index4` ON `autocapital`.`students_status` (`is_main` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`tests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`tests` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`tests` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `title` VARCHAR(255) NOT NULL,
  `course` INT(11) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `attempt_limit` INT(11) NOT NULL DEFAULT '0',
  `time_limit` INT(11) NULL DEFAULT '0',
  `completed_score` INT(11) NULL DEFAULT NULL,
  `question_from` CHAR(1) NOT NULL DEFAULT 'A',
  `question_amount` INT(11) NOT NULL DEFAULT '0',
  `passage_type` TINYINT(3) NOT NULL DEFAULT '0',
  `is_random_questions` TINYINT(1) NOT NULL DEFAULT '1',
  `is_random_answers` TINYINT(1) NOT NULL DEFAULT '1',
  `is_approved` TINYINT(1) NOT NULL DEFAULT '1',
  `is_include_self_test` TINYINT(1) NOT NULL DEFAULT '0',
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `old_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `t_course_fk`
    FOREIGN KEY (`course`)
    REFERENCES `autocapital`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Тесты курсов';

CREATE INDEX `course_indx` ON `autocapital`.`tests` (`course` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`tests_questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`tests_questions` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`tests_questions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `test_id` INT(11) NOT NULL,
  `date_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Дата создания',
  `is_multiple` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Множественный ли ответ',
  `title` VARCHAR(255) NOT NULL,
  `sort` INT(11) NOT NULL DEFAULT '0',
  `description` TEXT NULL DEFAULT NULL,
  `point` INT(11) NOT NULL DEFAULT '1' COMMENT 'Количество баллов за правильный ответ',
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `old_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_questions_1`
    FOREIGN KEY (`test_id`)
    REFERENCES `autocapital`.`tests` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Вопросы тестов';

CREATE INDEX `test_id` ON `autocapital`.`tests_questions` (`test_id` ASC);

CREATE INDEX `is_multiple` ON `autocapital`.`tests_questions` (`is_multiple` ASC);

CREATE INDEX `is_active` ON `autocapital`.`tests_questions` (`is_active` ASC);

CREATE INDEX `index5` ON `autocapital`.`tests_questions` (`old_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`tests_answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`tests_answers` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`tests_answers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `is_correct` TINYINT(4) NOT NULL DEFAULT '0' COMMENT 'Правильный ли ответ',
  `question_id` INT(11) NOT NULL,
  `sort` INT(11) NULL DEFAULT NULL,
  `old_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_answers_1`
    FOREIGN KEY (`question_id`)
    REFERENCES `autocapital`.`tests_questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Ответы тестов';

CREATE INDEX `question_id` ON `autocapital`.`tests_answers` (`question_id` ASC);

CREATE INDEX `index3` ON `autocapital`.`tests_answers` (`old_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`tests_attempts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`tests_attempts` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`tests_attempts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `test_id` INT(11) NOT NULL,
  `student_id` INT(11) NOT NULL,
  `date_start` DATETIME NOT NULL,
  `date_end` DATETIME NULL DEFAULT NULL,
  `is_time_expired` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Время вышло при прохождении теста',
  `is_completed` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Тест за�',
  `questions_count` INT(11) NOT NULL DEFAULT '0' COMMENT 'Количество вопросов',
  `scope` INT(11) NOT NULL DEFAULT '0' COMMENT 'Количество наб',
  `scope_max` INT(11) NOT NULL DEFAULT '0' COMMENT 'Максимальное количес�',
  `old_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tests_attempts_1`
    FOREIGN KEY (`test_id`)
    REFERENCES `autocapital`.`tests` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tests_attempts_2`
    FOREIGN KEY (`student_id`)
    REFERENCES `autocapital`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Попытки ответов на тесты';

CREATE INDEX `fk_attempts_1_idx` ON `autocapital`.`tests_attempts` (`test_id` ASC);

CREATE INDEX `fk_tests_attempts_2_idx` ON `autocapital`.`tests_attempts` (`student_id` ASC);

CREATE INDEX `index4` ON `autocapital`.`tests_attempts` (`old_id` ASC);

CREATE INDEX `index5` ON `autocapital`.`tests_attempts` (`is_completed` ASC);

CREATE INDEX `index6` ON `autocapital`.`tests_attempts` (`is_time_expired` ASC);

CREATE INDEX `index7` ON `autocapital`.`tests_attempts` (`date_start` ASC);

CREATE INDEX `index8` ON `autocapital`.`tests_attempts` (`date_end` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`tests_gradebook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`tests_gradebook` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`tests_gradebook` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_id` INT(11) NOT NULL,
  `test_id` INT(11) NOT NULL,
  `result` INT(11) NOT NULL COMMENT 'Лучший результат студента',
  `max_result` INT(11) NOT NULL COMMENT 'МАксимально возможный результат',
  `attempts_count` INT(11) NOT NULL COMMENT 'Количество попыток',
  `is_completed` TINYINT(1) NULL DEFAULT NULL COMMENT 'Пройден ли тест',
  `date_start` DATETIME NULL DEFAULT NULL,
  `date_end` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tests_gradebook_1`
    FOREIGN KEY (`student_id`)
    REFERENCES `autocapital`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tests_gradebook_2`
    FOREIGN KEY (`test_id`)
    REFERENCES `autocapital`.`tests` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Лучшие результаты по попыткам тестов';

CREATE INDEX `index2` ON `autocapital`.`tests_gradebook` (`student_id` ASC);

CREATE INDEX `index3` ON `autocapital`.`tests_gradebook` (`test_id` ASC);

CREATE INDEX `index4` ON `autocapital`.`tests_gradebook` (`is_completed` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`tests_results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`tests_results` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`tests_results` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `attempt_id` INT(11) NOT NULL,
  `question_id` INT(11) NOT NULL,
  `answer_id` INT(11) NOT NULL COMMENT 'id ответа, который был выбран',
  `is_correct` TINYINT(1) NOT NULL COMMENT 'Правильный ли ',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Результаты ответов на конкретные вопросы ';


-- -----------------------------------------------------
-- Table `autocapital`.`user_authorization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`user_authorization` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`user_authorization` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `token` VARCHAR(45) NOT NULL,
  `last_time` DATETIME NOT NULL,
  `expired_time` DATETIME NOT NULL,
  `user_agent` VARCHAR(255) NULL DEFAULT NULL,
  `user_ip` VARCHAR(11) NOT NULL,
  `user_os` VARCHAR(255) NULL DEFAULT NULL,
  `session_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_autorisation_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `autocapital`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8
COMMENT = 'Авторизация пользователей на сайте ';

CREATE INDEX `index2` ON `autocapital`.`user_authorization` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`user_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`user_groups` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`user_groups` (
  `user_id` INT(11) NOT NULL,
  `group_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`, `group_id`),
  CONSTRAINT `ug_group_id_fk`
    FOREIGN KEY (`group_id`)
    REFERENCES `autocapital`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ug_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `autocapital`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Связь группы пользователей';

CREATE INDEX `ug_user_id_idx` ON `autocapital`.`user_groups` (`user_id` ASC);

CREATE INDEX `ug_group_id_idx` ON `autocapital`.`user_groups` (`group_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`dealers_controllers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`dealers_controllers` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`dealers_controllers` (
  `dealer_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`dealer_id`, `user_id`),
  CONSTRAINT `dc_dealer_id_fk`
    FOREIGN KEY (`dealer_id`)
    REFERENCES `autocapital`.`dealers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dc_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `autocapital`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Связь пользователи-контролёры предприятий';

CREATE INDEX `dc_dealer_idx` ON `autocapital`.`dealers_controllers` (`dealer_id` ASC);

CREATE INDEX `dc_user_idx` ON `autocapital`.`dealers_controllers` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `autocapital`.`students_posts_activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autocapital`.`students_posts_activities` ;

CREATE TABLE IF NOT EXISTS `autocapital`.`students_posts_activities` (
  `student_post_id` INT(11) NOT NULL,
  `activity_id` INT(11) NOT NULL,
  CONSTRAINT `fk_students_activities_1`
    FOREIGN KEY (`activity_id`)
    REFERENCES `autocapital`.`activities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_activities_2`
    FOREIGN KEY (`student_post_id`)
    REFERENCES `autocapital`.`students_posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Связь бренды студентов';

CREATE INDEX `fk_students_activities_2_idx` ON `autocapital`.`students_posts_activities` (`student_post_id` ASC);

CREATE INDEX `fk_students_activities_1_idx` ON `autocapital`.`students_posts_activities` (`activity_id` ASC);

USE `autocapital`;

DELIMITER $$

USE `autocapital`$$
DROP TRIGGER IF EXISTS `autocapital`.`students_certifications_BINS` $$
USE `autocapital`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `students_certifications_BINS`
BEFORE INSERT ON `students_certifications`
FOR EACH ROW
SET NEW.mark_percent = ROUND(NEW.mark / NEW.mark_max, 2)$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
